name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      password:
        required: true
        type: string
        
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Display Data
       run: echo "Username is ${{ inputs.username }}, Password is ${{ inputs.password }}" 
