name: PR_Merge

# Controls when the workflow will run
on:
 # Triggers the workflow on push or pull request events but only for the "main" branch

 push:
   branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Changeset deployed"
