name: Workflow to be invoked #1
on:
  workflow_call:
    inputs:
      NPM_AUTH_TOKEN:
        required: true
        type: string
  
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm test
        run: echo "NPM tests running, NPM Token is ${{ secrets.NPM_AUTH_TOKEN }}"
  

