name: Conditional Workflow Check
on:
  push:
   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Checks
        if: ${{ github.ref == 'ref/heads/main' }} && github.event_name == 'pull_request'
        run: echo "Lint checks based on conditional flow"
      - name: Create Release
        if: github.event_name == 'push' && ${{ github.ref == 'ref/heads/main' }}
        uses: actions/create-release@latest
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
