name: Conditional Workflow Check
on:
  push:
   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Checks
        if: ${{ github.ref == 'ref/heads/main' }} && github.event_name == 'pull_request'
        run: echo "Lint checks based on conditional flow"
      - name: Create Release
        if: github.event_name == 'push' && ${{ github.ref == 'ref/heads/main' }}
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
