name: Create release on tags
on:
  release:
    types: [published, created]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        run: echo "Release created"
