name: Create release on tags
on:
  release:
    types: [published, created, edited]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy Changeset on Release
        run: echo "Release deployed" 
