name: Conditional Workflow Check
on:
  push:
   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        if: ${{ github.ref == 'ref/heads/main' }} && github.repository == 'apoorvPC/privatecircle_repo' && github.event_name == 'pull_request'

        run: echo "Lint checks based on conditional flow"
      - name: Test
        run: echo "Testing workflow"
      - name: Deploy
        if: github.event_name == 'push'
        run: echo "Changeset deployed"
